name: step-seven-aks

on:
  push:
    branches:
    - main
    # paths:
    # - step-seven/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # setting this up:
    # https://github.com/Azure/login
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # could possibly use this instead
    # https://github.com/Azure/aks-set-context
    # - name: Get AKS credentials
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.0.72
    #     inlineScript: |
    #       az aks get-credentials -n athens-stage -g athens
    # - name: Deploy
    #   uses: deliverybot/helm # TODO: what version number???
    #   with:
    #     exec: |
    #       helm upgrade xkcd \
    #         ./step-seven/charts \
    #         --install \
    #         --wait \
    #         --atomic \
    #         --namespace=xkcd \
    #         --set=app.name=xkcd \
    #         --values=./step-seven/chart/values.yaml
    #     # kubeconfig: '${{ secrets.KUBECONFIG }}'
    #     kubeconfig: '$(cat ~/.kube/config)'
