name: step-seven-aks

on:
  push:
    branches:
    - main
    # paths:
    # - step-seven/*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # setting this up:
    # https://github.com/Azure/login
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # could possibly use this instead
    # https://github.com/Azure/aks-set-context
    - name: Get AKS credentials
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az aks get-credentials -n athens-stage -g athens
    - name: Set KUBECONFIG env variable
      run: |
          KUBECONFIG=$(cat /root/.kube/config)
          echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV
    - name: Deploy
      uses: deliverybot/helm@v1 # TODO: what version number???
      with:
        release: 'xkcd'
        namespace: 'xkcd'
        chart: './step-seven/chart'
        token: '${{ github.token }}'
        values: |
          name: foobar
        value-files: >-
          ["values.yaml"]
      env:
        KUBECONFIG_FILE: '$KUBECONFIG'
